import re

# Comprehensive whitelist for technical books
# Including: tech terms, system names, people names, acronyms, book titles

tech_terms = {
    # Distributed systems concepts
    'consensus', 'quorum', 'raft', 'paxos', 'bft', 'pbft', 'crdt', 'byzantine',
    'replication', 'replicated', 'sharding', 'shard', 'partition', 'partitioning',
    'checkpoint', 'checkpointing', 'failover', 'fallback', 'recovery',
    'consistency', 'eventual', 'linearizable', 'linearizability', 'causal',
    'sequential', 'serializability', 'isolation', 'durability', 'atomicity',
    'atomic', 'transaction', 'transactions', 'commit', 'rollback', 'abort',
    'two', 'phase', 'commit', 'prewrite', 'precommit', 'timestamp', 'mvcc',
    'lsm', 'sstable', 'memtable', 'compaction', 'wal', 'log', 'logs',
    'leader', 'follower', 'candidate', 'leaderless', 'primary', 'secondary',
    'read', 'write', 'reads', 'writes', 'readconcern', 'writeconcern',
    'heartbeat', 'election', 'term', 'vote', 'appendentries', 'entries',
    'client', 'server', 'request', 'response', 'ack', 'nack', 'timeout',
    'retry', 'idempotency', 'idempotent', 'replay', 'deduplication',
    'gossip', 'broadcast', 'multicast', 'anycast', 'unicast',
    'snapshot', 'restore', 'backup', 'restore', 'disaster',
    'latency', 'throughput', 'bandwidth', 'rps', 'qps', 'tail',
    'availability', 'cap', 'acid', 'base', 'slo', 'sli', 'sla',
    'rpo', 'rto', 'mttr', 'mtbf',
    # Database terms
    'database', 'table', 'tables', 'schema', 'index', 'indexing',
    'query', 'scan', 'join', 'filter', 'aggregate', 'aggregation',
    'nosql', 'newsql', 'oltp', 'olap', 'htap',
    'dynamo', 'cassandra', 'scylladb', 'mongodb', 'redis', 'riak',
    'spanner', 'bigtable', 'foundationdb', 'faunadb', 'cockroachdb',
    'tidb', 'tikv', 'mysql', 'postgresql', 'postgres', 'sqlite',
    'oracle', 'cosmos', 'yugabytedb', 'dsql', 'crdbe',
    'percolator', 'megastore', 'calvin', 'epaxos', 'viewstamped',
    'cop', 'cops', 'eiger',
    # Consensus protocols
    'tendermint', 'bullshark', 'mysticeti', 'narwhal', 'sui', 'aptos',
    'diem', 'hotstuff', 'zab', 'chubby', 'paxos',
    # Storage
    'rocksdb', 'leveldb', 'ssd', 'hdd', 'rdma', 'nvlink',
    'disaggregated', 'disaggregation', 'serverless', 'neon',
    'firecracker', 'container', 'pod', 'kubernetes', 'docker',
    # Streaming
    'kafka', 'flink', 'spark', 'trino', 'presto', 'bigquery',
    'stream', 'streams', 'streaming', 'topic', 'offset',
    'producer', 'consumer', 'subscriber', 'publisher', 'publishes',
    'source', 'sink', 'connector', 'pipeline', 'pipelining',
    'exactly', 'once', 'atleast', 'atmost',
    # Networking
    'tcp', 'udp', 'http', 'https', 'rpc', 'grpc', 'rest', 'graphql',
    'cdn', 'dns', 'tls', 'mtls', 'ssl', 'websocket', 'webassembly',
    'envoy', 'istio', 'linkerd', 'gateway', 'mesh', 'sidecar',
    'balancer', 'proxy', 'reverse', 'forward', 'route', 'routing',
    'circuit', 'breaker', 'hystrix', 'fallback', 'retry',
    'cloudflare', 'fastly', 'nginx', 'haproxy',
    # Observability
    'tracing', 'traces', 'tracer', 'span', 'spans', 'trace',
    'metrics', 'logging', 'logs', 'tempo', 'datadog', 'honeycomb',
    'opentelemetry', 'collector', 'exporter', 'agent',
    # ML/AI
    'vllm', 'sglang', 'nim', 'tgi', 'fireworks', 'anyscale',
    'pagedattention', 'radixattention', 'lmcache', 'mooncake',
    'llama', 'moe', 'inference', 'serving', 'distserve', 'splitwise',
    'nvidia', 'gpu', 'cpu', 'ram', 'l1', 'l2', 'l3',
    'tokens', 'attention', 'transformer', 'embedding',
    # People names
    'kleppmann', 'tobias', 'ongaro', 'lynch', 'fischer', 'paterson',
    'chandra', 'toueg', 'lamport', 'castro', 'liskov', 'howard',
    'buchman', 'dwork', 'malkhi', 'aguilera', 'bronson', 'kulkarni',
    'kingsbury', 'jones', 'schwartz', 'bloom', 'spiegelman',
    'ousterhout', 'howard', 'lloyd', 'kraft', 'reilly',
    'femi', 'yuki', 'diego', 'chandy', 'lamport', 'martin',
    'hardenberg', 'mcgranaghan', 'wiggins', 'neil', 'kyle',
    'heidi', 'nora', 'robin', 'jones', 'paulo', 'deutsch',
    'van', 'der', 'yin', 'avva', 'demirbas', 'leone', 'madappa',
    'reilly', 'schwartz',
    # Places
    'frankfurt', 'tokyo', 'lagos', 'brooklyn', 'seattle', 'harvard',
    'san', 'amazon', 'azure', 'gcp', 'windows',
    # Product/system names
    'aurora', 'stratus', 'glide', 'snowflake', 'patroni',
    'hashicorp', 'consul', 'etcd', 'zookeeper',
    'netflix', 'roblox', 'slack', 'datadog',
    'toxiproxy', 'chaos', 'monkey',
    'socratopia', 'scholar', 'google',
    # Code/programming
    'def', 'const', 'class', 'func', 'return', 'import', 'async',
    'await', 'true', 'false', 'null', 'none', 'self', 'this',
    'python', 'rust', 'git', 'java', 'go', 'cpp',
    'sdk', 'api', 'apis', 'apiw', 'apie',
    'config', 'flag', 'flags', 'feature', 'toggle',
    'test', 'testing', 'benchmark', 'benchmarks',
    'bug', 'bugs', 'issue', 'issues',
    'linter', 'lint', 'check', 'checks', 'checklist',
    'runbook', 'playbook', 'handbook',
    # Common tech abbreviations
    'rps', 'qps', 'p99', 'p95', 'p50', 'rtt', 'mttr', 'mtbf',
    'rpo', 'rto', 'slo', 'sli', 'sla', 'soc', 'sre',
    'roi', 'usd', 'gbit',
    'ebpf', 'vpc', 'rbac', 'sso', 'auth', 'tls', 'mtls',
    'ddia', 'etl', 'cdc',
    # CRDT terms
    'automerge', 'rga', 'lww', 'hlc', 'dot', 'dots', 'dotted',
    'vector', 'vectors', 'clock', 'clocks', 'skew',
    # Misc tech
    'tombstone', 'memtable', 'sstable', 'wal', 'lsn',
    'vnode', 'tablet', 'bucket', 'shard', 'spine',
    'leaf', 'root', 'parent', 'child', 'sibling',
    'head', 'tail', 'next', 'prev', 'previous',
    'first', 'last', 'mid', 'middle',
    'add', 'remove', 'delete', 'insert', 'update',
    'merge', 'split', 'compaction',
    'lease', 'lock', 'locks', 'mutex', 'semaphore',
    'queue', 'stack', 'heap', 'buffer', 'cache',
    'worker', 'workers', 'orchestrator', 'orchestrated', 'choreographed',
    'coordinator', 'participant', 'acceptors', 'proposer',
    'sender', 'receiver', 'recv', 'deliver', 'delivered', 'deliverable',
    'flooding', 'broadcast', 'gossip',
    'sequencer', 'paxos', 'raft', 'zab',
    'fsync', 'fsync',
    'ledger', 'accounts', 'account', 'balance', 'transfer',
    'payment', 'merchant', 'customer', 'credit', 'fraud',
    'bank', 'order', 'orders',
    'item', 'items', 'cart', 'checkout',
    'doc', 'docs', 'document', 'documents',
    'text', 'list', 'set', 'map', 'pair',
    'event', 'events', 'message', 'messages', 'msg',
    'job', 'jobs', 'task', 'tasks', 'schedule', 'scheduled', 'scheduling',
    'rollout', 'rollback', 'revert', 'deploy', 'deployment',
    'revision', 'version', 'versions',
    'diff', 'patch', 'merge',
    'outbox', 'inbox',
    'schema', 'schemas',
    'tenant', 'tenants',
    'secret', 'secrets', 'key', 'keys',
    'token', 'tokens', 'jwt',
    'certificate', 'certificates', 'cert',
    'probe', 'health', 'readiness', 'liveness',
    'startup', 'shutdown',
    'outlier', 'outliers',
    'balancer', 'load', 'loadbalancer',
    'edge', 'origin', 'egress', 'ingress',
    'fan', 'fanout', 'fanin',
    'hop', 'hops', 'rtt',
    'region', 'regional', 'zone', 'zones', 'cell', 'cells',
    'geo', 'global', 'local',
    'rebalance', 'rebalancing',
    'locality', 'affinity',
    'burst', 'bursts', 'sustained',
    'shedding', 'load', 'shed',
    'priority', 'priorities',
    'cross', 'inter', 'intra',
    'sub', 'subgraph',
    'multi', 'split',
    'dotted', 'dot',
    'pair', 'pairing',
    'half', 'halfopen',
    'closed', 'open',
    'happy', 'sad',
    'wins', 'loses',
    'stale', 'fresh',
    'strong', 'weak',
    'strict', 'sloppy',
    'durable', 'ephemeral',
    'persistent', 'transient',
    'monotonic', 'nonmonotonic',
    'uniform', 'uniformity',
    'weighted', 'weighting',
    'located', 'colocated',
    'aware', 'awareness',
    'bound', 'bounds', 'bounded',
    'unbounded',
    'shared', 'dedicated',
    'dedicated', 'exclusive',
    'fair', 'unfair',
    'simple', 'complex',
    'trivial', 'nontrivial',
    'provably',
    'practical',
    'efficient',
    'minimal',
    'operational',
    'structured',
    'unstructured',
    'serial',
    'parallel', 'parallelism',
    'concurrent', 'concurrency',
    'synchronous', 'asynchronous', 'async',
    'blocking', 'nonblocking',
    'deterministic', 'nondeterministic',
    'probabilistic',
    'static', 'dynamic',
    'stateful', 'stateless',
    'state',
    'system', 'systems',
    'service', 'services',
    'application', 'applications',
    'software', 'hardware',
    'network', 'networks',
    'storage', 'memory',
    'compute', 'computing',
    'cluster', 'clusters',
    'node', 'nodes',
    'process', 'processes',
    'thread', 'threads',
    'core', 'cores',
    'kernel', 'user',
    'web', 'mobile',
    'enterprise', 'consumer',
    'cloud', 'onpremise',
    'source', 'open',
    'feature', 'features',
    'profile', 'profiles',
    'metric', 'metrics',
    'score', 'scores',
    'level', 'levels',
    'tier', 'tiers', 'tiered',
    'layer', 'layers',
    'foundation', 'foundations',
    'corner', 'corners',
    'edge', 'edges',
    'side', 'sides',
    'front', 'back',
    'top', 'bottom',
    'left', 'right',
    'inner', 'outer',
    'upper', 'lower',
    'main',
    'post', 'pre',
    'over', 'under',
    'out', 'off',
    'on', 'in',
    'up', 'down',
    'any', 'all',
    'each', 'every',
    'some', 'none',
    'yes', 'no',
    'true', 'false',
    'hello', 'world',
    'room', 'rooms',
    'brain', 'brains',
    'monkey', 'monkeys',
    'storm', 'storms',
    'snow',
    'flight',
    'fire',
    'bridge',
    'tunnel',
    'path', 'paths',
    'route', 'routes',
    'trip',
    'tour',
    'walk',
    'step', 'steps',
    'round',
    'phase', 'phases',
    'stage', 'stages',
    'point', 'points',
    'mark', 'marker', 'markers',
    'flag', 'flags',
    'tag', 'tags',
    'label', 'labels',
    'field', 'fields',
    'attribute', 'attributes',
    'property', 'properties',
    'value', 'values',
    'type', 'types',
    'size', 'sizes',
    'count', 'counts',
    'number', 'numbers',
    'total',
    'partial',
    'full',
    'empty', 'emptyset',
    'null', 'nil',
    'zero',
    'one',
    'new', 'old',
    'current', 'previous', 'next',
    'latest',
    'best', 'worst',
    'high', 'low',
    'fast', 'slow',
    'big', 'small',
    'short', 'long',
    'near', 'far',
    'early', 'late',
    'before', 'after',
    'now', 'then',
    'here', 'there',
    'where',
    'when',
    'how',
    'why',
    'what',
    'who',
    'via',
    'using',
    'through',
    'over',
    'under',
    'between',
    'within',
    'without',
    'against',
    'per',
    'each',
    'both',
    'either',
    'neither',
    'only',
    'even',
    'still',
    'already',
    'yet',
    'just',
    'also',
    'too',
    'very',
    'quite',
    'rather',
    'somewhat',
    'almost',
    'nearly',
    'about',
    'around',
    'approximately',
    'roughly',
    'exactly',
    'precisely',
    'approximately',
    'approx',
    'versus',
    'vs',
    'like',
    'unlike',
    'such',
    'same',
    'different',
    'similar',
    'opposite',
    'reverse',
    'inverse',
    'converse',
    'obverse',
    'counter',
    'counterpart',
    'analogous',
    'equivalent',
    'identical',
    'equal',
    'unequal',
    'proportional',
    'disproportionate',
    'relative',
    'absolute',
    'nominal',
    'ordinal',
    'cardinal',
    'fractional',
    'integral',
    'differential',
    'marginal',
    'incremental',
    'decremental',
    'exponential',
    'logarithmic',
    'linear',
    'nonlinear',
    'quadratic',
    'cubic',
    'polynomial',
    'constant',
    'variable',
    'parameter',
    'argument',
    'function',
    'method',
    'procedure',
    'routine',
    'subroutine',
    'callback',
    'handler',
    'listener',
    'listeners',
    'listens',
    'notifies',
    'notify',
    'publishes',
    'subscribes',
    'watches',
    'observes',
    'monitors',
    'tracks',
    'traces',
    'logs',
    'records',
    'registers',
    'stores',
    'loads',
    'loaded',
    'saves',
    'fetches',
    'retrieves',
    'gets',
    'puts',
    'posts',
    'deletes',
    'removes',
    'adds',
    'inserts',
    'updates',
    'modifies',
    'changes',
    'creates',
    'destroys',
    'drops',
    'builds',
    'compiles',
    'runs',
    'executes',
    'starts',
    'stops',
    'pauses',
    'resumes',
    'waits',
    'sleeps',
    'wakes',
    'signals',
    'broadcasts',
    'multicasts',
    'unicasts',
    'anycasts',
    'sends',
    'receives',
    'delivers',
    'forwards',
    'routes',
    'switches',
    'connects',
    'disconnects',
    'binds',
    'unbinds',
    'listens',
    'accepts',
    'rejects',
    'denies',
    'grants',
    'revokes',
    'authorizes',
    'authenticates',
    'verifies',
    'validates',
    'checks',
    'confirms',
    'acknowledges',
    'nacks',
    'replies',
    'responds',
    'requests',
    'asks',
    'queries',
    'searches',
    'finds',
    'looks',
    'scans',
    'seeks',
    'sorts',
    'orders',
    'groups',
    'aggregates',
    'counts',
    'sums',
    'averages',
    'minimizes',
    'maximizes',
    'optimizes',
    'tunes',
    'profiles',
    'benchmarks',
    'tests',
    'debugs',
    'troubleshoots',
    'diagnoses',
    'analyzes',
    'investigates',
    'explores',
    'discovers',
    'learns',
    'trains',
    'fits',
    'predicts',
    'infers',
    'estimates',
    'approximates',
    'calculates',
    'computes',
    'evaluates',
    'assesses',
    'measures',
    'gauges',
    'meters',
    'sensors',
    'detectors',
    'indicators',
    'signals',
    'alarms',
    'alerts',
    'notifications',
    'messages',
    'events',
    'incidents',
    'issues',
    'bugs',
    'errors',
    'faults',
    'failures',
    'crashes',
    'panics',
    'exceptions',
    'warnings',
    'info',
    'debug',
    'trace',
    'audit',
    'review',
    'inspection',
    'examination',
    'verification',
    'validation',
    'certification',
    'accreditation',
    'approval',
    'authorization',
    'authentication',
    'identification',
    'recognition',
    'detection',
    'prevention',
    'protection',
    'defense',
    'offense',
    'attack',
    'vulnerability',
    'threat',
    'risk',
    'hazard',
    'danger',
    'safety',
    'security',
    'privacy',
    'confidentiality',
    'integrity',
    'availability',
    'reliability',
    'dependability',
    'resilience',
    'robustness',
    'fault',
    'tolerance',
    'redundancy',
    'replication',
    'backup',
    'archive',
    'retention',
    'purge',
    'cleanup',
    'garbage',
    'collection',
    'compaction',
    'merge',
    'split',
    'shard',
    'partition',
    'replica',
    'clone',
    'copy',
    'duplicate',
    'redundant',
    'spare',
    'standby',
    'hot',
    'warm',
    'cold',
    'active',
    'passive',
    'primary',
    'secondary',
    'tertiary',
    'master',
    'slave',
    'leader',
    'follower',
    'candidate',
    'voter',
    'proposer',
    'acceptor',
    'learner',
    'coordinator',
    'participant',
    'witness',
    'observer',
    'client',
    'server',
    'proxy',
    'gateway',
    'router',
    'switch',
    'bridge',
    'tunnel',
    'repeater',
    'amplifier',
    'repeater',
    'multiplexer',
    'demultiplexer',
    'encoder',
    'decoder',
    'serializer',
    'deserializer',
    'parser',
    'formatter',
    'validator',
    'sanitizer',
    'normalizer',
    'transformer',
    'converter',
    'adapter',
    'wrapper',
    'facade',
    'proxy',
    'delegate',
    'dispatcher',
    'router',
    'resolver',
    'locator',
    'finder',
    'matcher',
    'filter',
    'selector',
    'projector',
    'reducer',
    'mapper',
    'collector',
    'aggregator',
    'accumulator',
    'buffer',
    'cache',
    'queue',
    'stack',
    'deque',
    'heap',
    'tree',
    'graph',
    'node',
    'edge',
    'vertex',
    'link',
    'pointer',
    'reference',
    'iterator',
    'enumerator',
    'generator',
    'yield',
    'stream',
    'flow',
    'pipe',
    'channel',
    'port',
    'socket',
    'endpoint',
    'interface',
    'api',
    'protocol',
    'scheme',
    'format',
    'encoding',
    'decoding',
    'compression',
    'decompression',
    'encryption',
    'decryption',
    'hashing',
    'signing',
    'verification',
    'certification',
    'key',
    'certificate',
    'token',
    'credential',
    'secret',
    'password',
    'pin',
    'otp',
    'mfa',
    'sso',
    'saml',
    'oauth',
    'openid',
    'jwt',
    'session',
    'cookie',
    'header',
    'headers',
    'body',
    'payload',
    'content',
    'data',
    'metadata',
    'schema',
    'model',
    'entity',
    'object',
    'record',
    'row',
    'column',
    'field',
    'attribute',
    'property',
    'value',
    'type',
    'class',
    'instance',
    'prototype',
    'template',
    'blueprint',
    'pattern',
    'design',
    'architecture',
    'structure',
    'framework',
    'library',
    'package',
    'module',
    'component',
    'service',
    'microservice',
    'endpoint',
    'resource',
    'asset',
    'artifact',
    'binary',
    'image',
    'container',
    'vm',
    'machine',
    'server',
    'host',
    'node',
    'pod',
    'cluster',
    'datacenter',
    'region',
    'zone',
    'rack',
    'blade',
    'server',
    'instance',
    'replica',
    'shard',
    'partition',
    'replica',
    'node',
    'peer',
    'neighbor',
    'adjacent',
    'nearby',
    'remote',
    'local',
    'global',
    'regional',
    'central',
    'distributed',
    'decentralized',
    'federated',
    'hybrid',
    'multi',
    'cross',
    'inter',
    'intra',
    'trans',
    'meta',
    'proto',
    'pre',
    'post',
    'over',
    'under',
    'out',
    'in',
    'on',
    'off',
    'up',
    'down',
    'back',
    'front',
    'side',
    'top',
    'bottom',
    'left',
    'right',
    'inner',
    'outer',
    'upper',
    'lower',
    'main',
    'sub',
    'super',
    'hyper',
    'ultra',
    'mega',
    'macro',
    'micro',
    'mini',
    'nano',
    'pico',
    'femto',
    'atto',
    'zepto',
    'yocto',
}

# Book title words that are OK
book_title_words = {
    'designing', 'data', 'intensive', 'applications',
    'system', 'design', 'interview', 'volume',
    'distributed', 'systems', 'principles', 'paradigms',
}

# Common short words already in original whitelist
common_ok = {
    'the', 'and', 'for', 'with', 'from', 'that', 'this', 'are', 'was', 'were',
    'has', 'had', 'have', 'not', 'but', 'all', 'can', 'will', 'one', 'two',
    'your', 'our', 'my', 'his', 'her', 'its', 'their',
    'you', 'we', 'they', 'he', 'she', 'it',
    'is', 'be', 'as', 'at', 'by', 'or', 'if', 'so', 'do', 'did',
    'an', 'no', 'of', 'to', 'in', 'on', 'up',
}

# Combine all whitelists
all_ok = tech_terms | book_title_words | common_ok

# Add all words from common_ok in the original scan script
all_ok |= {
    'app', 'apps', 'kpi', 'kpis', 'ui', 'ux', 'api', 'rss', 'pdf', 'url',
    'ceo', 'cfo', 'coo', 'cto', 'hr', 'adhd', 'fmri', 'bpm',
    'instagram', 'facebook', 'twitter', 'tiktok', 'whatsapp', 'snapchat',
    'youtube', 'google', 'apple', 'android', 'ios', 'chrome', 'safari', 'firefox',
    'redis', 'postgresql', 'postgres', 'mongodb', 'cassandra', 'cockroachdb',
    'spanner', 'kafka', 'docker', 'kubernetes', 'grpc', 'protobuf', 'json', 'xml', 'yaml',
    'cap', 'acid', 'base', 'slo', 'sli', 'sla', 'ttl', 'jwt', 'cdn', 'dns',
    'raft', 'paxos', 'bft', 'crdt', 'hlc', 'lww', 'mvcc', 'lsm',
    'ntp', 'utc', 'gps', 'sql', 'tcp', 'udp', 'http', 'https', 'rpc',
    'vllm', 'newsql', 'oltp', 'olap', 'truetime',
}

for fname, label in [('_issues_systemdesign.txt', '系统设计思维'), ('_issues_distributed.txt', '分布式系统')]:
    with open(fname, 'r', encoding='utf-8') as f:
        content = f.read()
    
    pattern = r'=== (\w+) \((\d+) occurrences\) ===\n(.*?)(?=\n=== |\Z)'
    matches = re.findall(pattern, content, re.DOTALL)
    
    print(f'\n{"="*60}')
    print(f'{label} — 需要检查的普通词（非技术术语/非人名/非系统名）：')
    print(f'{"="*60}')
    
    found = []
    for word, count, body in matches:
        wl = word.lower()
        if wl not in all_ok and int(count) > 0:
            found.append((word, int(count), body))
    
    print(f'共 {len(found)} 个词需要检查：\n')
    for word, count, body in found:
        # Only show first 2 context lines for brevity
        lines = body.strip().split('\n')[:2]
        print(f'=== {word} ({count} occurrences) ===')
        for l in lines:
            print(l.strip())
        print()
