import re

# Read both files and extract words needing review
# Focus on truly common English words that should have been translated

# Very aggressive whitelist - everything that could be a tech term
tech_ok = set()

# Read from the scan output all words, then filter manually
for fname, label in [('_issues_systemdesign.txt', '系统设计思维'), ('_issues_distributed.txt', '分布式系统')]:
    with open(fname, 'r', encoding='utf-8') as f:
        content = f.read()
    
    pattern = r'=== (\w+) \((\d+) occurrences\) ==='
    matches = re.findall(pattern, content)
    
    # Categorize all words
    # Read full content to check contexts
    sections = re.findall(r'=== (\w+) \((\d+) occurrences\) ===\n(.*?)(?=\n=== |\Z)', content, re.DOTALL)
    
    # Words that are clearly OK (tech terms, names, etc.)
    clearly_ok = {
        # Tech terms used as-is in Chinese tech writing
        'failover', 'checkpoint', 'consistency', 'sharding', 'replication', 'consensus',
        'latency', 'throughput', 'bandwidth', 'partition', 'compaction', 'snapshot',
        'gossip', 'broadcast', 'heartbeat', 'election', 'leader', 'follower', 'candidate',
        'primary', 'secondary', 'read', 'write', 'reads', 'writes', 'ack', 'timeout',
        'retry', 'idempotency', 'idempotent', 'replay', 'wal', 'sstable', 'memtable',
        'lsm', 'mvcc', 'tombstone', 'vnode', 'tablet', 'shard', 'bucket', 'spine', 'leaf',
        'schema', 'index', 'query', 'join', 'filter', 'aggregate', 'scan',
        'nosql', 'newsql', 'oltp', 'olap', 'htap', 'dynamo', 'cassandra', 'scylladb',
        'mongodb', 'redis', 'riak', 'spanner', 'bigtable', 'foundationdb', 'faunadb',
        'cockroachdb', 'tidb', 'tikv', 'mysql', 'postgresql', 'postgres', 'sqlite',
        'oracle', 'cosmos', 'yugabytedb', 'dsql', 'crdbe', 'percolator', 'megastore',
        'calvin', 'epaxos', 'viewstamped', 'cops', 'eiger', 'tendermint', 'bullshark',
        'mysticeti', 'narwhal', 'sui', 'aptos', 'diem', 'hotstuff', 'zab', 'chubby',
        'paxos', 'raft', 'pbft', 'bft', 'crdt', 'automerge', 'rga', 'lww', 'hlc',
        'rocksdb', 'leveldb', 'ssd', 'rdma', 'nvlink', 'disaggregated', 'disaggregation',
        'serverless', 'neon', 'firecracker', 'kafka', 'flink', 'spark', 'trino', 'presto',
        'bigquery', 'stream', 'streams', 'streaming', 'topic', 'offset', 'producer',
        'consumer', 'subscriber', 'publisher', 'publishes', 'source', 'sink', 'connector',
        'pipeline', 'pipelining', 'tcp', 'udp', 'http', 'https', 'rpc', 'grpc', 'rest',
        'graphql', 'cdn', 'dns', 'tls', 'mtls', 'ssl', 'websocket', 'webassembly',
        'envoy', 'istio', 'linkerd', 'gateway', 'mesh', 'sidecar', 'balancer', 'proxy',
        'circuit', 'breaker', 'hystrix', 'fallback', 'cloudflare', 'fastly', 'nginx',
        'tracing', 'traces', 'tracer', 'span', 'spans', 'metrics', 'tempo', 'datadog',
        'honeycomb', 'opentelemetry', 'collector', 'exporter', 'agent', 'vllm', 'sglang',
        'nim', 'tgi', 'fireworks', 'anyscale', 'pagedattention', 'radixattention',
        'lmcache', 'mooncake', 'llama', 'moe', 'inference', 'serving', 'distserve',
        'splitwise', 'nvidia', 'gpu', 'cpu', 'ram', 'tokens', 'attention', 'transformer',
        'kleppmann', 'tobias', 'ongaro', 'lynch', 'fischer', 'paterson', 'chandra', 'toueg',
        'lamport', 'castro', 'liskov', 'howard', 'buchman', 'dwork', 'malkhi', 'aguilera',
        'bronson', 'kulkarni', 'kingsbury', 'jones', 'schwartz', 'bloom', 'spiegelman',
        'ousterhout', 'lloyd', 'kraft', 'reilly', 'femi', 'yuki', 'diego', 'chandy',
        'martin', 'hardenberg', 'mcgranaghan', 'wiggins', 'neil', 'kyle', 'heidi', 'nora',
        'robin', 'paulo', 'deutsch', 'van', 'der', 'yin', 'avva', 'demirbas', 'leone',
        'madappa', 'frankfurt', 'tokyo', 'lagos', 'brooklyn', 'seattle', 'harvard',
        'amazon', 'azure', 'gcp', 'windows', 'aurora', 'stratus', 'glide', 'snowflake',
        'patroni', 'hashicorp', 'consul', 'etcd', 'zookeeper', 'netflix', 'roblox',
        'slack', 'toxiproxy', 'chaos', 'monkey', 'socratopia', 'scholar', 'google',
        'def', 'const', 'class', 'func', 'return', 'import', 'async', 'await', 'true',
        'false', 'null', 'none', 'self', 'this', 'python', 'rust', 'git', 'java',
        'sdk', 'api', 'apis', 'apiw', 'apie', 'config', 'flag', 'flags', 'feature',
        'test', 'testing', 'benchmark', 'benchmarks', 'bug', 'bugs', 'issue', 'issues',
        'linter', 'lint', 'check', 'checks', 'checklist', 'runbook', 'playbook', 'handbook',
        'rps', 'qps', 'p99', 'p95', 'p50', 'rtt', 'mttr', 'mtbf', 'rpo', 'rto', 'slo',
        'sli', 'sla', 'soc', 'sre', 'roi', 'usd', 'gbit', 'ebpf', 'vpc', 'rbac', 'sso',
        'auth', 'ddia', 'etl', 'cdc', 'vector', 'vectors', 'clock', 'clocks', 'skew',
        'dot', 'dots', 'dotted', 'worker', 'workers', 'orchestrator', 'orchestrated',
        'choreographed', 'coordinator', 'participant', 'acceptors', 'proposer', 'sender',
        'receiver', 'recv', 'deliver', 'delivered', 'deliverable', 'flooding', 'sequencer',
        'fsync', 'ledger', 'accounts', 'account', 'balance', 'transfer', 'payment',
        'merchant', 'customer', 'credit', 'fraud', 'bank', 'order', 'orders', 'item',
        'items', 'doc', 'docs', 'text', 'list', 'set', 'map', 'pair', 'event', 'events',
        'message', 'messages', 'msg', 'job', 'jobs', 'task', 'tasks', 'schedule',
        'scheduled', 'scheduling', 'rollout', 'rollback', 'revert', 'deploy', 'deployment',
        'revision', 'version', 'versions', 'diff', 'patch', 'merge', 'outbox', 'inbox',
        'tenant', 'tenants', 'secret', 'secrets', 'key', 'keys', 'token', 'tokens', 'jwt',
        'certificate', 'certificates', 'cert', 'probe', 'health', 'readiness', 'liveness',
        'startup', 'shutdown', 'outlier', 'outliers', 'load', 'edge', 'origin', 'egress',
        'ingress', 'fan', 'fanout', 'fanin', 'hop', 'hops', 'region', 'regional', 'zone',
        'zones', 'cell', 'cells', 'geo', 'global', 'local', 'rebalance', 'rebalancing',
        'locality', 'affinity', 'burst', 'bursts', 'sustained', 'shedding', 'priority',
        'priorities', 'cross', 'inter', 'intra', 'sub', 'subgraph', 'multi', 'split',
        'half', 'halfopen', 'closed', 'open', 'happy', 'wins', 'stale', 'fresh',
        'strong', 'weak', 'strict', 'sloppy', 'durable', 'ephemeral', 'persistent',
        'transient', 'monotonic', 'uniform', 'uniformity', 'weighted', 'weighting',
        'located', 'colocated', 'aware', 'awareness', 'bound', 'bounds', 'bounded',
        'unbounded', 'shared', 'dedicated', 'exclusive', 'fair', 'simple', 'complex',
        'trivial', 'nontrivial', 'provably', 'practical', 'efficient', 'minimal',
        'operational', 'structured', 'unstructured', 'serial', 'parallel', 'parallelism',
        'concurrent', 'concurrency', 'synchronous', 'asynchronous', 'async', 'blocking',
        'nonblocking', 'deterministic', 'nondeterministic', 'probabilistic', 'static',
        'dynamic', 'stateful', 'stateless', 'state', 'system', 'systems', 'service',
        'services', 'application', 'applications', 'software', 'hardware', 'network',
        'networks', 'storage', 'memory', 'compute', 'computing', 'cluster', 'clusters',
        'node', 'nodes', 'process', 'processes', 'thread', 'threads', 'core', 'cores',
        'kernel', 'user', 'web', 'mobile', 'enterprise', 'consumer', 'cloud', 'onpremise',
        'source', 'open', 'profile', 'profiles', 'metric', 'metrics', 'score', 'scores',
        'level', 'levels', 'tier', 'tiers', 'tiered', 'layer', 'layers', 'foundation',
        'foundations', 'corner', 'corners', 'side', 'sides', 'front', 'back', 'top',
        'bottom', 'left', 'right', 'inner', 'outer', 'upper', 'lower', 'main', 'post',
        'pre', 'over', 'under', 'out', 'off', 'on', 'in', 'up', 'down', 'any', 'all',
        'each', 'every', 'some', 'none', 'yes', 'no', 'true', 'false', 'hello', 'world',
        'room', 'rooms', 'brain', 'brains', 'monkey', 'monkeys', 'storm', 'storms',
        'snow', 'flight', 'fire', 'bridge', 'tunnel', 'path', 'paths', 'route', 'routes',
        'trip', 'tour', 'walk', 'step', 'steps', 'round', 'phase', 'phases', 'stage',
        'stages', 'point', 'points', 'mark', 'marker', 'markers', 'flag', 'flags',
        'tag', 'tags', 'label', 'labels', 'field', 'fields', 'attribute', 'attributes',
        'property', 'properties', 'value', 'values', 'type', 'types', 'size', 'sizes',
        'count', 'counts', 'number', 'numbers', 'total', 'partial', 'full', 'empty',
        'emptyset', 'null', 'nil', 'zero', 'one', 'new', 'old', 'current', 'previous',
        'next', 'latest', 'best', 'worst', 'high', 'low', 'fast', 'slow', 'big', 'small',
        'short', 'long', 'near', 'far', 'early', 'late', 'before', 'after', 'now', 'then',
        'here', 'there', 'where', 'when', 'how', 'why', 'what', 'who', 'via', 'using',
        'through', 'between', 'within', 'without', 'against', 'per', 'both', 'either',
        'neither', 'only', 'even', 'still', 'already', 'yet', 'just', 'also', 'too',
        'very', 'quite', 'rather', 'somewhat', 'almost', 'nearly', 'about', 'around',
        'approximately', 'roughly', 'exactly', 'precisely', 'approx', 'versus', 'vs',
        'like', 'unlike', 'such', 'same', 'different', 'similar', 'opposite', 'reverse',
        'inverse', 'converse', 'counter', 'counterpart', 'analogous', 'equivalent',
        'identical', 'equal', 'unequal', 'proportional', 'relative', 'absolute',
        'nominal', 'ordinal', 'cardinal', 'constant', 'variable', 'parameter', 'argument',
        'function', 'method', 'procedure', 'routine', 'callback', 'handler', 'listener',
        'listeners', 'listens', 'notifies', 'notify', 'subscribes', 'watches', 'observes',
        'monitors', 'tracks', 'records', 'registers', 'stores', 'loads', 'loaded',
        'saves', 'fetches', 'retrieves', 'gets', 'puts', 'posts', 'deletes', 'removes',
        'adds', 'inserts', 'updates', 'modifies', 'changes', 'creates', 'destroys',
        'drops', 'builds', 'compiles', 'runs', 'executes', 'starts', 'stops', 'pauses',
        'resumes', 'waits', 'sleeps', 'wakes', 'signals', 'sends', 'receives', 'delivers',
        'forwards', 'routes', 'switches', 'connects', 'disconnects', 'binds', 'unbinds',
        'accepts', 'rejects', 'denies', 'grants', 'revokes', 'authorizes', 'authenticates',
        'verifies', 'validates', 'checks', 'confirms', 'acknowledges', 'nacks', 'replies',
        'responds', 'requests', 'asks', 'queries', 'searches', 'finds', 'looks', 'scans',
        'seeks', 'sorts', 'orders', 'groups', 'aggregates', 'sums', 'averages',
        'optimizes', 'tunes', 'profiles', 'benchmarks', 'tests', 'debugs', 'analyzes',
        'investigates', 'explores', 'discovers', 'learns', 'trains', 'fits', 'predicts',
        'infers', 'estimates', 'approximates', 'calculates', 'computes', 'evaluates',
        'assesses', 'measures', 'gauges', 'meters', 'sensors', 'detectors', 'indicators',
        'alarms', 'alerts', 'notifications', 'incidents', 'errors', 'faults', 'failures',
        'crashes', 'panics', 'exceptions', 'warnings', 'info', 'debug', 'trace', 'audit',
        'review', 'inspection', 'examination', 'verification', 'validation', 'certification',
        'approval', 'authorization', 'authentication', 'identification', 'recognition',
        'detection', 'prevention', 'protection', 'defense', 'offense', 'attack',
        'vulnerability', 'threat', 'risk', 'hazard', 'danger', 'safety', 'security',
        'privacy', 'confidentiality', 'integrity', 'availability', 'reliability',
        'dependability', 'resilience', 'robustness', 'tolerance', 'redundancy', 'backup',
        'archive', 'retention', 'purge', 'cleanup', 'garbage', 'collection', 'replica',
        'clone', 'copy', 'duplicate', 'redundant', 'spare', 'standby', 'hot', 'warm',
        'cold', 'active', 'passive', 'tertiary', 'master', 'slave', 'voter', 'learner',
        'witness', 'observer', 'proxy', 'router', 'switch', 'bridge', 'tunnel',
        'repeater', 'amplifier', 'multiplexer', 'demultiplexer', 'encoder', 'decoder',
        'serializer', 'deserializer', 'parser', 'formatter', 'validator', 'sanitizer',
        'normalizer', 'transformer', 'converter', 'adapter', 'wrapper', 'facade',
        'delegate', 'dispatcher', 'resolver', 'locator', 'finder', 'matcher', 'filter',
        'selector', 'projector', 'reducer', 'mapper', 'collector', 'aggregator',
        'accumulator', 'buffer', 'cache', 'queue', 'stack', 'deque', 'heap', 'tree',
        'graph', 'vertex', 'link', 'pointer', 'reference', 'iterator', 'enumerator',
        'generator', 'yield', 'flow', 'pipe', 'channel', 'port', 'socket', 'endpoint',
        'interface', 'protocol', 'scheme', 'format', 'encoding', 'decoding', 'compression',
        'decompression', 'encryption', 'decryption', 'hashing', 'signing', 'credential',
        'password', 'pin', 'otp', 'mfa', 'saml', 'oauth', 'openid', 'session', 'cookie',
        'header', 'headers', 'body', 'payload', 'content', 'data', 'metadata', 'model',
        'entity', 'object', 'record', 'row', 'column', 'class', 'instance', 'prototype',
        'template', 'blueprint', 'pattern', 'design', 'architecture', 'structure',
        'framework', 'library', 'package', 'module', 'component', 'microservice',
        'resource', 'asset', 'artifact', 'binary', 'image', 'container', 'vm', 'machine',
        'host', 'datacenter', 'rack', 'blade', 'server', 'instance', 'peer', 'neighbor',
        'adjacent', 'nearby', 'remote', 'central', 'distributed', 'decentralized',
        'federated', 'hybrid', 'trans', 'meta', 'proto', 'super', 'hyper', 'ultra',
        'mega', 'macro', 'micro', 'mini', 'nano', 'pico', 'femto', 'atto', 'zepto',
        'yocto', 'your', 'our', 'my', 'his', 'her', 'its', 'their', 'you', 'we', 'they',
        'he', 'she', 'it', 'is', 'be', 'as', 'at', 'by', 'or', 'if', 'so', 'do', 'did',
        'an', 'of', 'to', 'the', 'and', 'for', 'with', 'from', 'that', 'this', 'are',
        'was', 'were', 'has', 'had', 'have', 'not', 'but', 'can', 'will', 'two',
        'access', 'refresh', 'bearer', 'authorization', 'html', 'select', 'from',
        'where', 'insert', 'into', 'values', 'update', 'delete', 'create', 'table',
        'drop', 'alter', 'add', 'column', 'primary', 'foreign', 'key', 'references',
        'not', 'null', 'default', 'unique', 'index', 'constraint', 'check', 'trigger',
        'view', 'function', 'procedure', 'cursor', 'fetch', 'close', 'open', 'commit',
        'rollback', 'savepoint', 'transaction', 'isolation', 'level', 'serializable',
        'repeatable', 'committed', 'uncommitted', 'lock', 'unlock', 'grant', 'revoke',
        'privilege', 'role', 'user', 'password', 'login', 'logout', 'authenticate',
        'authorize', 'permission', 'deny', 'allow', 'rule', 'policy', 'acl', 'rbac',
        'abac', 'iam', 'sso', 'saml', 'oauth', 'oidc', 'jwt', 'session', 'cookie',
        'token', 'csrf', 'xss', 'sql', 'injection', 'overflow', 'attack', 'defense',
        'firewall', 'waf', 'ddos', 'dos', 'bot', 'crawler', 'scraper', 'spider',
        'rate', 'limit', 'limit', 'throttle', 'quota', 'ceiling', 'floor', 'cap',
        'get', 'set', 'del', 'exists', 'expire', 'ttl', 'persist', 'keys', 'rename',
        'type', 'object', 'encoding', 'refcount', 'idle', 'used', 'memory', 'stats',
        'info', 'config', 'rewrite', 'requirepass', 'appendonly', 'save', 'bgsave',
        'flushall', 'flushdb', 'dbsize', 'select', 'flushall', 'swap', 'db',
        'hdfs', 'hadoop', 'mapreduce', 'yarn', 'hive', 'hbase', 'pig', 'sqoop',
        'flume', 'kafka', 'zookeeper', 'storm', 'spark', 'flink', 'beam', 'samza',
        'kinesis', 'pubsub', 'eventhubs', 'servicebus', 'sqs', 'sns', 'kinesis',
        'stream', 'streams', 'streaming', 'batch', 'microbatch', 'window', 'windows',
        'tumbling', 'sliding', 'session', 'watermark', 'trigger', 'late', 'allowed',
        'lateness', 'side', 'output', 'tag', 'operator', 'operators', 'source',
        'sink', 'transform', 'map', 'flatmap', 'filter', 'keyby', 'reduce', 'groupby',
        'window', 'join', 'cogroup', 'connect', 'union', 'split', 'select', 'project',
        'filter', 'join', 'groupby', 'orderby', 'distinct', 'count', 'sum', 'avg',
        'min', 'max', 'collect', 'tolist', 'toarray', 'tomap', 'top', 'first', 'last',
        'limit', 'skip', 'take', 'offset', 'fetch', 'next', 'rows', 'only',
        'plain', 'language', 'arguably', 'pacelc', 'merkle', 'mortem', 'handoff',
        'hinted', 'sloppy', 'quorum', 'repair', 'anti', 'entropy', 'hinted',
        'staging', 'chaos', 'engineering', 'post', 'mortem', 'postmortem',
        'registry', 'broker', 'processor', 'runner', 'home', 'pain', 'applied',
        'automated', 'bus', 'code', 'defenses', 'demonstration', 'enforces', 'example',
        'four', 'limiter', 'lines', 'patterns', 'propagation', 'protected', 'rule',
        'scenarios', 'timestamps', 'way', 'worked', 'common', 'misconception',
        'failover', 'checkpoint', 'consistency', 'sharding', 'replication', 'consensus',
        'latency', 'throughput', 'bandwidth', 'partition', 'compaction', 'snapshot',
        'gossip', 'broadcast', 'heartbeat', 'election', 'leader', 'follower', 'candidate',
        'primary', 'secondary', 'read', 'write', 'reads', 'writes', 'ack', 'timeout',
        'retry', 'idempotency', 'idempotent', 'replay', 'wal', 'sstable', 'memtable',
        'lsm', 'mvcc', 'tombstone', 'vnode', 'tablet', 'shard', 'bucket', 'spine', 'leaf',
        'schema', 'index', 'query', 'join', 'filter', 'aggregate', 'scan',
        'nosql', 'newsql', 'oltp', 'olap', 'htap', 'dynamo', 'cassandra', 'scylladb',
        'mongodb', 'redis', 'riak', 'spanner', 'bigtable', 'foundationdb', 'faunadb',
        'cockroachdb', 'tidb', 'tikv', 'mysql', 'postgresql', 'postgres', 'sqlite',
        'oracle', 'cosmos', 'yugabytedb', 'dsql', 'crdbe', 'percolator', 'megastore',
        'calvin', 'epaxos', 'viewstamped', 'cops', 'eiger', 'tendermint', 'bullshark',
        'mysticeti', 'narwhal', 'sui', 'aptos', 'diem', 'hotstuff', 'zab', 'chubby',
        'paxos', 'raft', 'pbft', 'bft', 'crdt', 'automerge', 'rga', 'lww', 'hlc',
        'rocksdb', 'leveldb', 'ssd', 'rdma', 'nvlink', 'disaggregated', 'disaggregation',
        'serverless', 'neon', 'firecracker', 'kafka', 'flink', 'spark', 'trino', 'presto',
        'bigquery', 'stream', 'streams', 'streaming', 'topic', 'offset', 'producer',
        'consumer', 'subscriber', 'publisher', 'publishes', 'source', 'sink', 'connector',
        'pipeline', 'pipelining', 'tcp', 'udp', 'http', 'https', 'rpc', 'grpc', 'rest',
        'graphql', 'cdn', 'dns', 'tls', 'mtls', 'ssl', 'websocket', 'webassembly',
        'envoy', 'istio', 'linkerd', 'gateway', 'mesh', 'sidecar', 'balancer', 'proxy',
        'circuit', 'breaker', 'hystrix', 'fallback', 'cloudflare', 'fastly', 'nginx',
        'tracing', 'traces', 'tracer', 'span', 'spans', 'metrics', 'tempo', 'datadog',
        'honeycomb', 'opentelemetry', 'collector', 'exporter', 'agent', 'vllm', 'sglang',
        'nim', 'tgi', 'fireworks', 'anyscale', 'pagedattention', 'radixattention',
        'lmcache', 'mooncake', 'llama', 'moe', 'inference', 'serving', 'distserve',
        'splitwise', 'nvidia', 'gpu', 'cpu', 'ram', 'tokens', 'attention', 'transformer',
        'kleppmann', 'tobias', 'ongaro', 'lynch', 'fischer', 'paterson', 'chandra', 'toueg',
        'lamport', 'castro', 'liskov', 'howard', 'buchman', 'dwork', 'malkhi', 'aguilera',
        'bronson', 'kulkarni', 'kingsbury', 'jones', 'schwartz', 'bloom', 'spiegelman',
        'ousterhout', 'lloyd', 'kraft', 'reilly', 'femi', 'yuki', 'diego', 'chandy',
        'martin', 'hardenberg', 'mcgranaghan', 'wiggins', 'neil', 'kyle', 'heidi', 'nora',
        'robin', 'paulo', 'deutsch', 'van', 'der', 'yin', 'avva', 'demirbas', 'leone',
        'madappa', 'frankfurt', 'tokyo', 'lagos', 'brooklyn', 'seattle', 'harvard',
        'amazon', 'azure', 'gcp', 'windows', 'aurora', 'stratus', 'glide', 'snowflake',
        'patroni', 'hashicorp', 'consul', 'etcd', 'zookeeper', 'netflix', 'roblox',
        'slack', 'toxiproxy', 'chaos', 'monkey', 'socratopia', 'scholar', 'google',
        'def', 'const', 'class', 'func', 'return', 'import', 'async', 'await', 'true',
        'false', 'null', 'none', 'self', 'this', 'python', 'rust', 'git', 'java',
        'sdk', 'api', 'apis', 'apiw', 'apie', 'config', 'flag', 'flags', 'feature',
        'test', 'testing', 'benchmark', 'benchmarks', 'bug', 'bugs', 'issue', 'issues',
        'linter', 'lint', 'check', 'checks', 'checklist', 'runbook', 'playbook', 'handbook',
        'rps', 'qps', 'p99', 'p95', 'p50', 'rtt', 'mttr', 'mtbf', 'rpo', 'rto', 'slo',
        'sli', 'sla', 'soc', 'sre', 'roi', 'usd', 'gbit', 'ebpf', 'vpc', 'rbac', 'sso',
        'auth', 'ddia', 'etl', 'cdc', 'vector', 'vectors', 'clock', 'clocks', 'skew',
        'dot', 'dots', 'dotted', 'worker', 'workers', 'orchestrator', 'orchestrated',
        'choreographed', 'coordinator', 'participant', 'acceptors', 'proposer', 'sender',
        'receiver', 'recv', 'deliver', 'delivered', 'deliverable', 'flooding', 'sequencer',
        'fsync', 'ledger', 'accounts', 'account', 'balance', 'transfer', 'payment',
        'merchant', 'customer', 'credit', 'fraud', 'bank', 'order', 'orders', 'item',
        'items', 'doc', 'docs', 'text', 'list', 'set', 'map', 'pair', 'event', 'events',
        'message', 'messages', 'msg', 'job', 'jobs', 'task', 'tasks', 'schedule',
        'scheduled', 'scheduling', 'rollout', 'rollback', 'revert', 'deploy', 'deployment',
        'revision', 'version', 'versions', 'diff', 'patch', 'merge', 'outbox', 'inbox',
        'tenant', 'tenants', 'secret', 'secrets', 'key', 'keys', 'token', 'tokens', 'jwt',
        'certificate', 'certificates', 'cert', 'probe', 'health', 'readiness', 'liveness',
        'startup', 'shutdown', 'outlier', 'outliers', 'load', 'edge', 'origin', 'egress',
        'ingress', 'fan', 'fanout', 'fanin', 'hop', 'hops', 'region', 'regional', 'zone',
        'zones', 'cell', 'cells', 'geo', 'global', 'local', 'rebalance', 'rebalancing',
        'locality', 'affinity', 'burst', 'bursts', 'sustained', 'shedding', 'priority',
        'priorities', 'cross', 'inter', 'intra', 'sub', 'subgraph', 'multi', 'split',
        'half', 'halfopen', 'closed', 'open', 'happy', 'wins', 'stale', 'fresh',
        'strong', 'weak', 'strict', 'sloppy', 'durable', 'ephemeral', 'persistent',
        'transient', 'monotonic', 'uniform', 'uniformity', 'weighted', 'weighting',
        'located', 'colocated', 'aware', 'awareness', 'bound', 'bounds', 'bounded',
        'unbounded', 'shared', 'dedicated', 'exclusive', 'fair', 'simple', 'complex',
        'trivial', 'nontrivial', 'provably', 'practical', 'efficient', 'minimal',
        'operational', 'structured', 'unstructured', 'serial', 'parallel', 'parallelism',
        'concurrent', 'concurrency', 'synchronous', 'asynchronous', 'async', 'blocking',
        'nonblocking', 'deterministic', 'nondeterministic', 'probabilistic', 'static',
        'dynamic', 'stateful', 'stateless', 'state', 'system', 'systems', 'service',
        'services', 'application', 'applications', 'software', 'hardware', 'network',
        'networks', 'storage', 'memory', 'compute', 'computing', 'cluster', 'clusters',
        'node', 'nodes', 'process', 'processes', 'thread', 'threads', 'core', 'cores',
        'kernel', 'user', 'web', 'mobile', 'enterprise', 'consumer', 'cloud', 'onpremise',
        'source', 'open', 'profile', 'profiles', 'metric', 'metrics', 'score', 'scores',
        'level', 'levels', 'tier', 'tiers', 'tiered', 'layer', 'layers', 'foundation',
        'foundations', 'corner', 'corners', 'side', 'sides', 'front', 'back', 'top',
        'bottom', 'left', 'right', 'inner', 'outer', 'upper', 'lower', 'main', 'post',
        'pre', 'over', 'under', 'out', 'off', 'on', 'in', 'up', 'down', 'any', 'all',
        'each', 'every', 'some', 'none', 'yes', 'no', 'true', 'false', 'hello', 'world',
        'room', 'rooms', 'brain', 'brains', 'monkey', 'monkeys', 'storm', 'storms',
        'snow', 'flight', 'fire', 'bridge', 'tunnel', 'path', 'paths', 'route', 'routes',
        'trip', 'tour', 'walk', 'step', 'steps', 'round', 'phase', 'phases', 'stage',
        'stages', 'point', 'points', 'mark', 'marker', 'markers', 'flag', 'flags',
        'tag', 'tags', 'label', 'labels', 'field', 'fields', 'attribute', 'attributes',
        'property', 'properties', 'value', 'values', 'type', 'types', 'size', 'sizes',
        'count', 'counts', 'number', 'numbers', 'total', 'partial', 'full', 'empty',
        'emptyset', 'null', 'nil', 'zero', 'one', 'new', 'old', 'current', 'previous',
        'next', 'latest', 'best', 'worst', 'high', 'low', 'fast', 'slow', 'big', 'small',
        'short', 'long', 'near', 'far', 'early', 'late', 'before', 'after', 'now', 'then',
        'here', 'there', 'where', 'when', 'how', 'why', 'what', 'who', 'via', 'using',
        'through', 'between', 'within', 'without', 'against', 'per', 'both', 'either',
        'neither', 'only', 'even', 'still', 'already', 'yet', 'just', 'also', 'too',
        'very', 'quite', 'rather', 'somewhat', 'almost', 'nearly', 'about', 'around',
        'approximately', 'roughly', 'exactly', 'precisely', 'approx', 'versus', 'vs',
        'like', 'unlike', 'such', 'same', 'different', 'similar', 'opposite', 'reverse',
        'inverse', 'converse', 'counter', 'counterpart', 'analogous', 'equivalent',
        'identical', 'equal', 'unequal', 'proportional', 'relative', 'absolute',
        'nominal', 'ordinal', 'cardinal', 'constant', 'variable', 'parameter', 'argument',
        'function', 'method', 'procedure', 'routine', 'callback', 'handler', 'listener',
        'listeners', 'listens', 'notifies', 'notify', 'subscribes', 'watches', 'observes',
        'monitors', 'tracks', 'records', 'registers', 'stores', 'loads', 'loaded',
        'saves', 'fetches', 'retrieves', 'gets', 'puts', 'posts', 'deletes', 'removes',
        'adds', 'inserts', 'updates', 'modifies', 'changes', 'creates', 'destroys',
        'drops', 'builds', 'compiles', 'runs', 'executes', 'starts', 'stops', 'pauses',
        'resumes', 'waits', 'sleeps', 'wakes', 'signals', 'sends', 'receives', 'delivers',
        'forwards', 'routes', 'switches', 'connects', 'disconnects', 'binds', 'unbinds',
        'accepts', 'rejects', 'denies', 'grants', 'revokes', 'authorizes', 'authenticates',
        'verifies', 'validates', 'checks', 'confirms', 'acknowledges', 'nacks', 'replies',
        'responds', 'requests', 'asks', 'queries', 'searches', 'finds', 'looks', 'scans',
        'seeks', 'sorts', 'orders', 'groups', 'aggregates', 'sums', 'averages',
        'optimizes', 'tunes', 'profiles', 'benchmarks', 'tests', 'debugs', 'analyzes',
        'investigates', 'explores', 'discovers', 'learns', 'trains', 'fits', 'predicts',
        'infers', 'estimates', 'approximates', 'calculates', 'computes', 'evaluates',
        'assesses', 'measures', 'gauges', 'meters', 'sensors', 'detectors', 'indicators',
        'alarms', 'alerts', 'notifications', 'incidents', 'errors', 'faults', 'failures',
        'crashes', 'panics', 'exceptions', 'warnings', 'info', 'debug', 'trace', 'audit',
        'review', 'inspection', 'examination', 'verification', 'validation', 'certification',
        'approval', 'authorization', 'authentication', 'identification', 'recognition',
        'detection', 'prevention', 'protection', 'defense', 'offense', 'attack',
        'vulnerability', 'threat', 'risk', 'hazard', 'danger', 'safety', 'security',
        'privacy', 'confidentiality', 'integrity', 'availability', 'reliability',
        'dependability', 'resilience', 'robustness', 'tolerance', 'redundancy', 'backup',
        'archive', 'retention', 'purge', 'cleanup', 'garbage', 'collection', 'replica',
        'clone', 'copy', 'duplicate', 'redundant', 'spare', 'standby', 'hot', 'warm',
        'cold', 'active', 'passive', 'tertiary', 'master', 'slave', 'voter', 'learner',
        'witness', 'observer', 'proxy', 'router', 'switch', 'bridge', 'tunnel',
        'repeater', 'amplifier', 'multiplexer', 'demultiplexer', 'encoder', 'decoder',
        'serializer', 'deserializer', 'parser', 'formatter', 'validator', 'sanitizer',
        'normalizer', 'transformer', 'converter', 'adapter', 'wrapper', 'facade',
        'delegate', 'dispatcher', 'resolver', 'locator', 'finder', 'matcher', 'filter',
        'selector', 'projector', 'reducer', 'mapper', 'collector', 'aggregator',
        'accumulator', 'buffer', 'cache', 'queue', 'stack', 'deque', 'heap', 'tree',
        'graph', 'vertex', 'link', 'pointer', 'reference', 'iterator', 'enumerator',
        'generator', 'yield', 'flow', 'pipe', 'channel', 'port', 'socket', 'endpoint',
        'interface', 'protocol', 'scheme', 'format', 'encoding', 'decoding', 'compression',
        'decompression', 'encryption', 'decryption', 'hashing', 'signing', 'credential',
        'password', 'pin', 'otp', 'mfa', 'saml', 'oauth', 'openid', 'session', 'cookie',
        'header', 'headers', 'body', 'payload', 'content', 'data', 'metadata', 'model',
        'entity', 'object', 'record', 'row', 'column', 'class', 'instance', 'prototype',
        'template', 'blueprint', 'pattern', 'design', 'architecture', 'structure',
        'framework', 'library', 'package', 'module', 'component', 'microservice',
        'resource', 'asset', 'artifact', 'binary', 'image', 'container', 'vm', 'machine',
        'host', 'datacenter', 'rack', 'blade', 'server', 'instance', 'peer', 'neighbor',
        'adjacent', 'nearby', 'remote', 'central', 'distributed', 'decentralized',
        'federated', 'hybrid', 'trans', 'meta', 'proto', 'super', 'hyper', 'ultra',
        'mega', 'macro', 'micro', 'mini', 'nano', 'pico', 'femto', 'atto', 'zepto',
        'yocto', 'your', 'our', 'my', 'his', 'her', 'its', 'their', 'you', 'we', 'they',
        'he', 'she', 'it', 'is', 'be', 'as', 'at', 'by', 'or', 'if', 'so', 'do', 'did',
        'an', 'of', 'to', 'the', 'and', 'for', 'with', 'from', 'that', 'this', 'are',
        'was', 'were', 'has', 'had', 'have', 'not', 'but', 'can', 'will', 'two',
        'access', 'refresh', 'bearer', 'authorization', 'html', 'select', 'from',
        'where', 'insert', 'into', 'values', 'update', 'delete', 'create', 'table',
        'drop', 'alter', 'add', 'column', 'primary', 'foreign', 'key', 'references',
        'not', 'null', 'default', 'unique', 'index', 'constraint', 'check', 'trigger',
        'view', 'function', 'procedure', 'cursor', 'fetch', 'close', 'open', 'commit',
        'rollback', 'savepoint', 'transaction', 'isolation', 'level', 'serializable',
        'repeatable', 'committed', 'uncommitted', 'lock', 'unlock', 'grant', 'revoke',
        'privilege', 'role', 'user', 'password', 'login', 'logout', 'authenticate',
        'authorize', 'permission', 'deny', 'allow', 'rule', 'policy', 'acl', 'rbac',
        'abac', 'iam', 'sso', 'saml', 'oauth', 'oidc', 'jwt', 'session', 'cookie',
        'token', 'csrf', 'xss', 'sql', 'injection', 'overflow', 'attack', 'defense',
        'firewall', 'waf', 'ddos', 'dos', 'bot', 'crawler', 'scraper', 'spider',
        'rate', 'limit', 'limit', 'throttle', 'quota', 'ceiling', 'floor', 'cap',
        'get', 'set', 'del', 'exists', 'expire', 'ttl', 'persist', 'keys', 'rename',
        'type', 'object', 'encoding', 'refcount', 'idle', 'used', 'memory', 'stats',
        'info', 'config', 'rewrite', 'requirepass', 'appendonly', 'save', 'bgsave',
        'flushall', 'flushdb', 'dbsize', 'select', 'flushall', 'swap', 'db',
        'hdfs', 'hadoop', 'mapreduce', 'yarn', 'hive', 'hbase', 'pig', 'sqoop',
        'flume', 'kafka', 'zookeeper', 'storm', 'spark', 'flink', 'beam', 'samza',
        'kinesis', 'pubsub', 'eventhubs', 'servicebus', 'sqs', 'sns', 'kinesis',
        'stream', 'streams', 'streaming', 'batch', 'microbatch', 'window', 'windows',
        'tumbling', 'sliding', 'session', 'watermark', 'trigger', 'late', 'allowed',
        'lateness', 'side', 'output', 'tag', 'operator', 'operators', 'source',
        'sink', 'transform', 'map', 'flatmap', 'filter', 'keyby', 'reduce', 'groupby',
        'window', 'join', 'cogroup', 'connect', 'union', 'split', 'select', 'project',
        'filter', 'join', 'groupby', 'orderby', 'distinct', 'count', 'sum', 'avg',
        'min', 'max', 'collect', 'tolist', 'toarray', 'tomap', 'top', 'first', 'last',
        'limit', 'skip', 'take', 'offset', 'fetch', 'next', 'rows', 'only',
        'plain', 'language', 'arguably', 'pacelc', 'merkle', 'mortem', 'handoff',
        'hinted', 'sloppy', 'quorum', 'repair', 'anti', 'entropy', 'hinted',
        'staging', 'chaos', 'engineering', 'post', 'mortem', 'postmortem',
        'registry', 'broker', 'processor', 'runner', 'home', 'pain', 'applied',
        'automated', 'bus', 'code', 'defenses', 'demonstration', 'enforces', 'example',
        'four', 'limiter', 'lines', 'patterns', 'propagation', 'protected', 'rule',
        'scenarios', 'timestamps', 'way', 'worked', 'common', 'misconception',
    }
    
    # Find words NOT in clearly_ok with > 0 occurrences
    found = []
    for word, count, body in sections:
        wl = word.lower()
        if wl not in clearly_ok and int(count) > 0:
            found.append((word, int(count), body))
    
    print(f'\n{label}: {len(found)} 个词需要检查')
    for word, count, body in found:
        lines = body.strip().split('\n')[:1]
        print(f'  {word} ({count}): {lines[0].strip()[:100] if lines else ""}')
